### ISSUE TITLE
segment fault with cluster and websocket

### ISSUE THREAD

**Issue by zh794390558** [hui6075/mosquitto-cluster#20]
```
Starting program: /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
1584615601: mosquitto version 1.5.0 starting
1584615601: Config loaded from /etc/mosquitto/mosquitto.conf.
1584615601: Opening websockets listen socket on port 8199.
1584615601: Opening ipv4 listen socket on port 8188.
1584615601: Opening ipv6 listen socket on port 8188.
1584615601: Warning: Address family not supported by protocol
1584615601: [CLUSTER] totally 2 remote nodes configured:
1584615601: [CLUSTER] Node(1):, ip:10.90.66.56, port:1883, 
1584615603: [CLUSTER INIT] node service maybe down, will reconnect later after 2 seconds..
1584615603: [CLUSTER INIT] node  service maybe down, will reconnect later after 2 seconds..
1584615607: [CLUSTER INIT] node  service maybe down, will reconnect later after 4 seconds..
1584615607: [CLUSTER INIT] node  service maybe down, will reconnect later after 4 seconds..

Program received signal SIGSEGV, Segmentation fault.
0x0000000000424e7c in sys_tree__update_clients (buf=0x7fffffffad60 "11 seconds", db=0x6348e0 <int_db>) at sys_tree.c:68
68              count_total = HASH_CNT(hh_id, db->contexts_by_id);
(gdb) bt
#0  0x0000000000424e7c in sys_tree__update_clients (buf=0x7fffffffad60 "11 seconds", db=0x6348e0 <int_db>) at sys_tree.c:68
#1  sys_tree__update (db=db@entry=0x6348e0 <int_db>, interval=<optimized out>, start_time=start_time@entry=47454812) at sys_tree.c:216
#2  0x0000000000416625 in mosquitto_main_loop (db=db@entry=0x6348e0 <int_db>, listensock=listensock@entry=0x71e570, listensock_count=listensock_count@entry=1, listener_max=<optimized out>) at loop.c:214
#3  0x0000000000405127 in main (argc=<optimized out>, argv=<optimized out>) at mosquitto.c:367
```

**Comment by cherho0** [comment]
me too  when i user websocket  it report Segmentation fault then crash
